version: '2'

services:
  feedback-agent-be:
    image: 'feedback-agent:latest'
    build:
      context: .
    container_name: feedback-agent-be
    expose:
      - 8080
    ports:
      - 8072:8080
    depends_on:
      - feedback-agent-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://feedback-agent-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - BEAM_PROXY_URI=http://dev_proxy2_1:8082
    networks:
      - teiler-ui
          
  feedback-agent-db:
    image: 'postgres:13.1-alpine'
    container_name: feedback-agent-db
    expose:
      - 5432
    #ports:
    #  - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - teiler-ui
  feedback-agent-ui:
    build:
      context: .
      dockerfile: Dockerfile_fba
    ports:
      - "8090:8090"
      
networks:
  teiler-ui:
    name: "teiler-ui"